application: lime-goatstone
version: 1
runtime: go
api_version: go1

handlers:

- url: /admin
  script: _go_app
  login: required

- url: /a
  script: _go_app
  login: required

- url: /tst
  script: _go_app

- url: /.*
  static_files:  index.html
  upload:  index.html
#  login: required
#  secure: always